//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbumMaker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class LightThemeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LightThemeSettings defaultInstance = ((LightThemeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LightThemeSettings())));
        
        public static LightThemeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#e6e6e6")]
        public string Background {
            get {
                return ((string)(this["Background"]));
            }
            set {
                this["Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string Foreground {
            get {
                return ((string)(this["Foreground"]));
            }
            set {
                this["Foreground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#c7c7c7")]
        public string ButtonBackground {
            get {
                return ((string)(this["ButtonBackground"]));
            }
            set {
                this["ButtonBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string ButtonForeground {
            get {
                return ((string)(this["ButtonForeground"]));
            }
            set {
                this["ButtonForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#6d95bf")]
        public string SideMenuBackground {
            get {
                return ((string)(this["SideMenuBackground"]));
            }
            set {
                this["SideMenuBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string SideMenuForeground {
            get {
                return ((string)(this["SideMenuForeground"]));
            }
            set {
                this["SideMenuForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#b2cbeb")]
        public string SideMenuButtonBackground {
            get {
                return ((string)(this["SideMenuButtonBackground"]));
            }
            set {
                this["SideMenuButtonBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string SideMenuButtonForeGround {
            get {
                return ((string)(this["SideMenuButtonForeGround"]));
            }
            set {
                this["SideMenuButtonForeGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string TextBoxBackground {
            get {
                return ((string)(this["TextBoxBackground"]));
            }
            set {
                this["TextBoxBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string TextBoxForeground {
            get {
                return ((string)(this["TextBoxForeground"]));
            }
            set {
                this["TextBoxForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#005eff")]
        public string LinkLabelForeground {
            get {
                return ((string)(this["LinkLabelForeground"]));
            }
            set {
                this["LinkLabelForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00bf53")]
        public string LinkLabelOnClick {
            get {
                return ((string)(this["LinkLabelOnClick"]));
            }
            set {
                this["LinkLabelOnClick"] = value;
            }
        }
    }
}
